### ISSUE TITLE
Modules looked up with HTTPS even when HTTP is specified

### ISSUE THREAD

**Issue by brandones** [joeldenning/import-map-overrides#9] opened 2019-12-16 14:35 UTC
See screenshots. In the first, the override is specified with `http://` and the browser returns a 404 for the same address but via https. In the second, the override is specified with `//` and the page is via http, but the override is looked up via https.

![Screenshot from 2019-12-12 00-43-31](https://user-images.githubusercontent.com/1031876/70914931-9db33b00-2021-11ea-9ea7-0970fa63b1fc.png)

![Screenshot from 2019-12-12 00-44-08](https://user-images.githubusercontent.com/1031876/70914934-9e4bd180-2021-11ea-8831-b7ba40f25539.png)

**Comment by joeldenning** [comment] 2019-12-16 14:51
I am unable to reproduce this. Did you make sure to refresh the page after setting the override?

On https openmrs-spa.org:

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/5524384/70915868-e7773380-1fd7-11ea-94fa-f311bd9ebce1.png">

On http localhost:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/5524384/70916286-ad5a6180-1fd8-11ea-983c-ece4a747a0f3.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/5524384/70916338-bba87d80-1fd8-11ea-8864-70a9124f1473.png">

I'm closing this since I can't reproduce the problem. Please reopen with a github repo that demonstrates the problem.

**Closed by joeldenning** 2019-12-16 14:51 UTC

**Comment by brandones** [comment] 2019-12-16 15:09
Oh, webpack-dev-server seems to be returning a 307 redirect from http to https. That would be the problem. Sorry for the lack of investigation before posting the issue.
